name: food_delivery_system
description: Food delivery system with customer and admin apps
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  # Cập nhật các bản Firebase hiện có lên bản cao hơn để tương thích
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.5.2

  # Các thư viện mới thêm với phiên bản phù hợp
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.2
  csv: ^6.0.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  fl_chart: ^0.69.0
  http: ^1.2.2
  firebase_storage: ^12.4.2
  image_picker: ^1.1.2
  # State Management
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true